version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taller-motos-db
    environment:
      POSTGRES_DB: taller_motos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - taller-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend/taller-motos-api
      dockerfile: Dockerfile
    container_name: taller-motos-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taller_motos_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - taller-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taller-motos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - taller-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  taller-network:
    driver: bridge
